version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    hostname: $MYSQL_HOST
    container_name: test_db
    volumes:
    - ./db_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"